repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.275
    hooks:
      - id: ruff
        # union of black + isort tools; and a few files that have pylint exclusions.
        args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/psf/black
  rev: 22.8.0
  hooks:
    - id: black
      language: python
      types: [python]


- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
