iterations: 100000
max_seq_len: 8
batch_size: 4
split: 0.9
vocab_file: "data/tokenizer/all_chars.json"
data_file: "data/corpus/shakespeare.txt"
save_path: "training/checkpoints/bigram.pt"
model_str: "bigram"
